### PR TITLE
Fix "message not found in the local cache" issue

### LINKED ISSUE #1549: message not found in the local cache
customer

> + additional topic (new bug found) : sometimes mails cannot be opened/displayed at first time (with an error message : "message not found in the local cache") in flowcrypt mail android application. The second time we try to open it, it works. [XXX] will send you examples/screenshots of the issue in a separate thread/mail.

(note - still waiting for separate email)

### PR DESCRIPTION
**Pull request by DenBond7**
This PR fixed "message not found in the local cache" issue.

close #1549

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt [hunk 1]
```diff
@@ -476,8 +477,16 @@ class MsgDetailsViewModel(
...
           if (result.status == Result.Status.SUCCESS) {
-            return@withContext MsgsCacheManager.getMsgSnapshot(messageEntity.id.toString())
-              ?: throw java.lang.NullPointerException("Message not found in the local cache")
+            var snapshot = MsgsCacheManager.getMsgSnapshot(messageEntity.id.toString())
+            if (snapshot == null) {
+              //due to realization of [DiskLruCache] we need to do a little delay
+              // while [DiskLruCache] is updating internal data
+              delay(500)
+              snapshot = MsgsCacheManager.getMsgSnapshot(messageEntity.id.toString())
+            }
```
Comment (tomholub) [inline FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/MsgDetailsViewModel.kt:486]: Maybe could be rewritten as do-while or similar? Or `for 1..50 { if (!null) return ...; delay ... } throw ...`

Then you set the interval at 50ms and try up to 50 times, which will be both faster (usually settles in 50ms, probably) and more reliable (waits up to 2.5 seconds instead of 0.5 to throw error)

**Review by tomholub — APPROVED** [review]
