### PR TITLE
Issue 1356 fix displaying inline images

### LINKED ISSUE #1356: Fix displaying inline images(Kotlin)
image

### PR DESCRIPTION
**Pull request by DenBond7**
This PR fixed displaying inline attachments

close #1356

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt [hunk 1]
```diff
@@ -198,11 +200,24 @@ abstract class BaseMessageDetailsFlowTest : BaseTest() {
...
+
+    val elementList = mutableListOf<Node>()
+    for (position in 0 until bodyElements.length) {
+      elementList.add(bodyElements.item(position))
+    }
+    val content = elementList.joinToString(separator = "") {
+      if (it.textContent.isNotEmpty()) {
+        it.textContent + "\n"
+      } else ""
+    }.trim()
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt:215]: maybe we can simplify getting content like below
```kt
val content = (0 until bodyElements.length)
      .asSequence()
      .map { bodyElements.item(it) }
      .filter { it.textContent.isNotEmpty() }
      .joinToString(separator = "\n") { it.textContent }
      .trim()
```

File: docker-mailserver/maildata_source/flowcrypt.test/has_msgs_no_backups/dovecot.list.index.log
Comment (ioanmo226) [inline docker-mailserver/maildata_source/flowcrypt.test/has_msgs_no_backups/dovecot.list.index.log:1]: Are those `log` files needed to be in git?
Maybe we can add it in gitignore if we don't need to store it in git?

**Review by ioanmo226 — COMMENTED** [review]
Initial quick review. will review deeply tomorrow

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt (hunk 1 above)
Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseMessageDetailsFlowTest.kt:215]: perfect!

File: docker-mailserver/maildata_source/flowcrypt.test/has_msgs_no_backups/dovecot.list.index.log
Comment (DenBond7) [reply docker-mailserver/maildata_source/flowcrypt.test/has_msgs_no_backups/dovecot.list.index.log:1]: We have an issue https://github.com/FlowCrypt/flowcrypt-android/issues/1610. Just need to do it ))

Comment (ioanmo226) [reply docker-mailserver/maildata_source/flowcrypt.test/has_msgs_no_backups/dovecot.list.index.log:1]: :-) Missed it

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt [hunk 2]
```diff
@@ -65,61 +69,109 @@ object RawBlockParser {
...
+                  if (b.toInt().toChar() == '-') {
+                    byteArray[index] = '+'.code.toByte()
+                  }
+
+                  if (b.toInt().toChar() == '_') {
+                    byteArray[index] = '/'.code.toByte()
+                  }
+                }
+                b?.let { byteArray.copyInto(it) }
+                return count
```
Comment (ioanmo226) [inline FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt:140]: Maybe write like below?
```kt
val count = super.read(b)
b?.forEachIndexed { index, byte ->
  when (byte.toInt().toChar()) {
    '-' -> b[index] = '+'.code.toByte()
    '_' -> b[index] = '/'.code.toByte()
  }
}
return count
```

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 3]
```diff
@@ -329,21 +330,38 @@ object PgpMsg {
...
                 isOpenPGPMimeSigned = isOpenPGPMimeSigned
               )
             )
           }
 
           val msgBlocks = processRawBlocks(
-            rawBlocks = detectedRawBlocks - attachmentRawBlocks.toSet(),
+            rawBlocks = detectedRawBlocks.toMutableList().apply {
+              inlineAttachmentRawBlock?.let { remove(it) }
+              inlineAttachmentRawBlock?.let { remove(it) }
```
Comment (ioanmo226) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:363]: Why did you call this twice?

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt (hunk 2 above)
Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt:140]: I like it. I will use it with a little modification. I still need to use a temp buffer.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt (hunk 3 above)
Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:363]: Thank you. It's a good one. Copy-paste issue.

Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:363]: Should be

```
attachmentRawBlock?.let { remove(it) }
inlineAttachmentRawBlock?.let { remove(it) }
```

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt (hunk 2 above)
Comment (ioanmo226) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt]: any reason why we need temp buffer?

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt (hunk 3 above)
Comment (ioanmo226) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt]: Sounds good!

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt (hunk 2 above)
Comment (ioanmo226) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt]: @DenBond7 Could you answer above question?

Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt]: Ah, sorry. I didn't see this question. 

I'd like to modify only the received bytes from the original input stream. It will be clear and describe what exactly I do. Because `b` from `override fun read(b: ByteArray?)` can contain some other bytes that I don't know how they should be handled(or not).

The main point of this method - replacing received bytes (`'-' ->  '+',  '_' ->  '/'`) from the input stream and write them to the given input byte array.

Comment (ioanmo226) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/RawBlockParser.kt]: I see. Thanks for your explanation

**Review by ioanmo226 — APPROVED** [review]
👍
