### PR TITLE
Fixed pgpainless usage

### LINKED ISSUE #2290: PGPainless threads issue
ref https://github.com/pgpainless/pgpainless/issues/365
ref https://github.com/pgpainless/pgpainless/pull/370

### PR DESCRIPTION
**Pull request by DenBond7**
This PR fixed `PGPainless` usage for multithreading purposes

close #2290 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+class SamePGPSignatureVerificationMultiThreadingTest {
+  @Test
+  fun testDecryptionInMultiThreads() {
+    val numberOfThreads = 10
+    val numberOfAttempts = 1000
+    val atomicInteger = AtomicInteger()
+
+    runBlocking {
+      executeInParallel(numberOfThreads) {
+        for (i in 0 until numberOfAttempts) {
```
Comment (ioanmo226) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt:36]: can use this
```kt
repeat(numberOfAttempts)
```

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+          doDecryption { decryptionResult ->
+            if (decryptionResult.exception == null) {
+              atomicInteger.addAndGet(1)
```
Comment (ioanmo226) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt:39]: `atomicInteger.incrementAndGet()`

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt [hunk 3]
```diff
@@ -0,0 +1,146 @@
...
+    assertNotEquals((numberOfThreads * numberOfAttempts).toLong(), atomicInteger.get().toLong())
+  }
+
+  private suspend fun executeInParallel(
+    threads: Int = 1,
+    action: suspend () -> Unit
+  ) = withContext(Dispatchers.IO)
+  {
+    val steps = mutableListOf<Deferred<Unit>>()
+    for (i in 0 until threads) {
```
Comment (ioanmo226) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/SamePGPSignatureVerificationMultiThreadingTest.kt:57]: `repeat(threads)`

**Review by ioanmo226 — APPROVED** [review]
