### PR TITLE
Issue 1475 do not show noname files

### LINKED ISSUE #1475: noname files related to OpenPGP should be recognized
To reproduce:

1) send a message from Browser Extension - Firefox and switch to `Rich Text (PGP/MIME)`. Add some bold text (ctrl+b)
2) receive the message on Android

Actual result:

image

Expected result: file with an empty name `application/pgp-encrypted` and content like `Version: 1` should be recognized as pgp-related and hidden.

### PR DESCRIPTION
**Pull request by DenBond7**
This PR added hiding a service att on the message details screen.

close #1475

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt [hunk 1]
```diff
@@ -1381,6 +1383,16 @@ class MessageDetailsFragment : BaseFragment(), ProgressBehaviour, View.OnClickLi
     })
   }
 
+  private fun isHiddenAtt(it: AttachmentInfo): Boolean {
+    return when {
```
Comment (IvanPizhenko) [inline FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt:1387]: could be method on `AttachmentInfo` and simplified to:
```kotlin
public fun isHidden() = name.isNullOrEmpty() && type.lowercase() == "application/pgp-encrypted; name=\"\""
```

**Review by IvanPizhenko — CHANGES_REQUESTED** [review]

File: FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt (hunk 1 above)
Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/fragment/MessageDetailsFragment.kt]: I've added changes. Please re-check

**Review by IvanPizhenko — APPROVED** [review]
