### PR TITLE
Issue 2180 fix password protected msg

### LINKED ISSUE #2180: Attachments are not readable in password-protected messages
reported by customer:

> after sending an email from the app to external users the attachment received on the Web Portal is corrupted, name is the right one but we can't open the image or characters are chinese symbols in .txt file

I reproduced it with password-protected email sent from android app. Works well for emails sent from iOS app

### PR DESCRIPTION
**Pull request by DenBond7**
This PR fixed sending password-protected messages with attachments

close #2180

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later (issue #2201 )

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt [hunk 1]
```diff
@@ -471,46 +476,61 @@ class SendMsgTest {
...
           store.getFolder(folderName).use { folder ->
             val imapFolder = (folder as IMAPFolder).apply { open(Folder.READ_ONLY) }
-            //get the latest message that we added to a folder recently
-            val mimeMessage = imapFolder.getMessage(imapFolder.messageCount) as MimeMessage
+            //get the message that we added to a folder recently
+            val mimeMessage = (if (useLast) {
+              imapFolder.messages.last()
+            } else {
+              imapFolder.messages.first()
+            }) as MimeMessage
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:508]: How about using `getOrElse`? Code length seems similar but `getOrElse` clearly expresses the intention of code i think
```kt
val mimeMessage = imapFolder.messages.getOrElse(
  if (useLast) imapFolder.messages.lastIndex else 0
) { throw NoSuchElementException("List is empty.") } as MimeMessage
```

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt [hunk 2]
```diff
@@ -471,46 +476,61 @@ class SendMsgTest {
...
               outgoingMessageInfo.ccRecipients?.toTypedArray(),
               mimeMessage.getRecipients(Message.RecipientType.CC)
             )
-            assertEquals(
-              ((outgoingMessageInfo.atts ?: emptyList()) + (outgoingMessageInfo.forwardedAtts
-                ?: emptyList())).size,
-              getAttCount(mimeMessage)
-            )
+            val expectedAttachmentCount = ((outgoingMessageInfo.atts ?: emptyList())
+                + (outgoingMessageInfo.forwardedAtts ?: emptyList())).size
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:529]: Can be simplified to I think
```kt
val expectedAttachmentCount = (outgoingMessageInfo.atts.orEmpty() + outgoingMessageInfo.forwardedAtts.orEmpty()).size
```

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt [hunk 3]
```diff
@@ -572,15 +592,33 @@ class SendMsgTest {
...
+            folder = folder.fullName,
+            uid = uid
+          )
+        })
+      }
 
-    //It's a real name of the first attachment of the message with Uid = 0
-    //in INBOX for default@flowcrypt.test
-    const val FORWARDED_ATTACHMENT_NAME = "flowcrypt-backup-defaultflowcrypttest.key"
+      return@runBlocking list.firstOrNull()
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:617]: Instead of mutable `list`, we can `checkExistingMsgOnServer` lambda to return the first attachment found.
```kt
checkExistingMsgOnServer(JavaEmailConstants.FOLDER_INBOX, outgoingMessageInfo) { folder, mimeMessage ->
    val uid = folder.getUID(mimeMessage)
    EmailUtil.getAttsInfoFromPart(mimeMessage).map {
        it.copy(email = addAccountToDatabaseRule.account.email, folder = folder.fullName, uid = uid)
    }.firstOrNull()
}
```

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt [hunk 4]
```diff
@@ -572,15 +592,33 @@ class SendMsgTest {
     )
   )
 
-  companion object {
-    const val ATTACHMENT_NAME = "test.txt"
+  private fun prepareForwardedAttachment(outgoingMessageInfo: OutgoingMessageInfo): AttachmentInfo? {
+    processOutgoingMessageInfo(outgoingMessageInfo)
+
+    val worker = TestListenableWorkerBuilder<MessagesSenderWorker>(context).build()
+    return runBlocking {
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:599]: `return` is unnecessary i think

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeScreenTest.kt [hunk 5]
```diff
@@ -68,4 +78,17 @@ abstract class BaseComposeScreenTest : BaseTest() {
         closeSoftKeyboard()
       )
   }
+
+  protected fun addAtt(att: File) {
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/base/BaseComposeScreenTest.kt:82]: `protected fun addAttachment(file: File)` would be more convinent function naming i think.

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt (hunk 2 above)
Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:529]: Nice, I like it.

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt [hunk 6]
```diff
@@ -0,0 +1,182 @@
...
+      pgpSecretKeyRing.encode(buffer)
+
+      atts.add(
+        TestGeneralUtil.createFileWithContent(
+          directory = directory,
+          fileName = ATTACHMENT_NAME_3,
+          inputStream = ByteArrayInputStream(buffer.toByteArray())
+        )
+      )
+    }
```
Comment (ioanmo226) [inline FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt:180]: How about do like this?
```kt
val buffer = ByteArrayOutputStream()
pgpSecretKeyRing.encode(buffer)
atts = listOf(
  TestGeneralUtil.createFileWithContent(directory, ATTACHMENT_NAME_1, "Text for filling the attached file".toInputStream()),
  TestGeneralUtil.createFileWithContent(directory, ATTACHMENT_NAME_2, "Text for filling the attached file".toInputStream()),
  TestGeneralUtil.createFileWithContent(directory, ATTACHMENT_NAME_3, ByteArrayInputStream(buffer.toByteArray()))
) as MutableList<File>
```

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt (hunk 3 above)
Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:617]: It requests additional changes in the called functions. But it will provide simplifications. I will add changes.

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt (hunk 4 above)
Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:599]: unfortunately, it is necessary here.

Comment (ioanmo226) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/SendMsgTest.kt:599]: I see. Can ignore comment then :-)

File: FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt (hunk 6 above)
Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt:180]: unfortunately, these lines are too long and will be formatted to 

```
val buffer = ByteArrayOutputStream()
      pgpSecretKeyRing.encode(buffer)
      atts = listOf(
        TestGeneralUtil.createFileWithContent(
          directory,
          ATTACHMENT_NAME_1,
          "Text for filling the attached file".toInputStream()
        ),
        TestGeneralUtil.createFileWithContent(
          directory,
          ATTACHMENT_NAME_2,
          "Text for filling the attached file".toInputStream()
        ),
        TestGeneralUtil.createFileWithContent(
          directory,
          ATTACHMENT_NAME_3,
          ByteArrayInputStream(buffer.toByteArray())
        )
      ) as MutableList<File>
```

Comment (DenBond7) [reply FlowCrypt/src/androidTest/java/com/flowcrypt/email/ui/SendPasswordProtectedMessageFlowTest.kt:180]: But anyway it looks better

**Comment by DenBond7** [comment]
@ioanmo226 I've added changes. Please take a look.

**Review by ioanmo226 — APPROVED** [review]
Looks good 👍
