### PR TITLE
Simplified error handling

### LINKED ISSUE #2241: Update API error format on Attester
ref https://github.com/FlowCrypt/flowcrypt-android/pull/2171#discussion_r1087703140

FES

```
{
  "code": 401,
  "message": "Authorization credentials required",
  "details": "io.javalin.http.UnauthorizedResponse"
}
```

Attester

```
{
    "error": {
        "message": "Body should not be empty"
    }
}
```

PubLookup
```
{
  "code": 404,
  "message": "Not Found",
  "details": ""
}
```

EKM

```
{
  "code": 401,
  "message": "Authorization credentials required",
  "details": "io.javalin.http.UnauthorizedResponse: Authorization credentials required"
}
```
Backend
```
{
    "error": {
        "code": 400,
        "message": "Wrong request received",
        "internal": "Please add a json body"
    }
}
```

@tomholub Is it possible to have the same error format for all APIs? it will help to simplify code.

It would be nice to have
(I prefer this one)
```
{
    "error": {
        "_": ""
        "_": "",
        ...
    }
}
```

or 

```
{
  "_": "",
  "_": ""
}
```

### PR DESCRIPTION
**Pull request by DenBond7**
This PR simplified error handling

close #2241

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt [hunk 1]
```diff
@@ -573,17 +573,17 @@ class PrivateKeysViewModel(application: Application) : AccountViewModel(applicat
 
     when (submitPubKeyResult.status) {
       Result.Status.SUCCESS -> {
-        val body = submitPubKeyResult.data
         when {
           isSilent -> {
-            body != null && (body.apiError == null || body.apiError.code !in 400..499)
+            submitPubKeyResult.apiError == null ||
+                (submitPubKeyResult.apiError.code != null && submitPubKeyResult.apiError.code !in 400..499)
```
Comment (ioanmo226) [inline FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt:579]: Can be simplified to below

```kt
submitPubKeyResult.apiError?.code?.let { it !in 400..499 } ?: true
```

Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/viewmodel/PrivateKeysViewModel.kt:579]: nice :+1:

**Review by ioanmo226 — APPROVED** [review]
👍
