### PR TITLE
Fixed opening messages in 'All Mail' folder + fix sync in 'All Mail' folder

### LINKED ISSUE #2995: Possible sync issue in "All Mail"
Description:

Emails deleted in "Inbox" still shows up from "All Mail", that when tapped to try and opening it will tell the user "thread is deleted or moved". It's important to note that the "All Mail" did a refresh on the first time hence it displays the deleted email in the "All Mail" list. This leaves the user in confusion as the deleted email in inbox should not be in "All Mail".

I initially thought it was working as expected but if we pay attention to detail, the "All Mail" already did a refresh so deleted email should already filter the deleted email and would not lead to such described scenario (not unless its a syncing issue such as the "All Mail" comes on a pre-load state).

Affected FlowCrypt Android app version: 1.6.2
Verified on: Android 13

Steps to reproduce:

1. Open FlowCrypt android app.
2. Go to "INBOX" and delete an email (regular or encrypted)
3. Go to "All Mail" and let it load.
4. It will display the recently deleted email.
5. Find the deleted email and try to access it - it will display the info toast saying `thread is deleted or moved.`

_Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQZTzbFvbcmJHzNbCZmbBfcnFlg_

### PR DESCRIPTION
**Pull request by DenBond7**
This PR Fixed opening messages in 'All Mail' folder + fix sync in 'All Mail' folder

close #2995 
----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt [hunk 1]
```diff
@@ -388,21 +394,34 @@ object GmailHistoryHandler {
...
+              historyLabelRemoved.labelIds?.contains(LABEL_TRASH) == true ||
+              historyLabelRemoved.labelIds?.contains(LABEL_SPAM) == true
+            ) {
+              deleteCandidates.remove(historyLabelRemoved.message.uid)
+              updateCandidates.remove(historyLabelRemoved.message.uid)
+              newCandidatesMap[historyLabelRemoved.message.uid] = historyLabelRemoved.message
               continue
             }
+          } else {
+            if (localFolder.fullName in (historyLabelRemoved.labelIds ?: emptyList())) {
```
Comment (ioanmo226) [inline FlowCrypt/src/main/java/com/flowcrypt/email/api/email/gmail/GmailHistoryHandler.kt:408]: Small comment. Let's add `lalelIds` variable in upcoming PR as `historyLabelRemoved.labelIds ?: emptyList<String>()` one is used several times 
```kt
val labelIds = historyLabelRemoved.labelIds ?: emptyList<String>()
```
