### PR TITLE
Fixed deprecation for GeneralUtil.isConnected().| #1943

### LINKED ISSUE #1943: Fix deprecation for GeneralUtil.isConnected()
https://stackoverflow.com/questions/57277759/getactivenetworkinfo-is-deprecated-in-api-29

### PR DESCRIPTION
**Pull request by DenBond7**
This PR Fixed deprecation for GeneralUtil.isConnected()

close #1943

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt [hunk 1]
```diff
@@ -89,17 +89,22 @@ class GeneralUtil {
...
-    //todo-denbond7 Need to fix deprecation
     fun isConnected(context: Context?): Boolean {
-      val cm = context?.getSystemService(Context.CONNECTIVITY_SERVICE) as? ConnectivityManager
-      val activeNetwork = cm?.activeNetworkInfo
-      return activeNetwork?.isConnected ?: false
+      val connectivityManager =
+        context?.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
+      val network = connectivityManager.activeNetwork ?: return false
+      val networkCapabilities = connectivityManager.getNetworkCapabilities(network) ?: return false
+      return when {
```
Comment (IvanPizhenko) [inline FlowCrypt/src/main/java/com/flowcrypt/email/util/GeneralUtil.kt:101]: can be just `return networkCapabilities ... ` (whole condition which results `true`)

**Review by IvanPizhenko — DISMISSED** [review]
Looks good, small simplification possible

**Review by IvanPizhenko — APPROVED** [review]
