### PR TITLE
issue #1057 Parsing/decrypting of complex PGP messages in Kotlin

### LINKED ISSUE #1057: parsing/decrypting of complex PGP messages in Kotlin
part of #1051 but first need to do https://github.com/FlowCrypt/flowcrypt-android/issues/1060

from https://github.com/FlowCrypt/flowcrypt-mobile-core/blob/master/source/mobile-interface/endpoints.ts

Unit tests to copy: everything that starts with `parseDecryptMsg` at https://github.com/FlowCrypt/flowcrypt-mobile-core/blob/master/source/test.ts

current implementation:

```ts
 public parseDecryptMsg = async (uncheckedReq: any, data: Buffers): Promise<Buffers> => {
    const { keys: kisWithPp, msgPwd, isEmail } = ValidateInput.parseDecryptMsg(uncheckedReq);
    const rawBlocks: MsgBlock[] = []; // contains parsed, unprocessed / possibly encrypted data
    let rawSigned: string | undefined = undefined;
    let subject: string | undefined = undefined;
    if (isEmail) {
      const { blocks, rawSignedContent, headers } = await Mime.process(Buf.concat(data));
      subject = String(headers['subject']);
      rawSigned = rawSignedContent;
      rawBlocks.push(...blocks);
    } else {
      rawBlocks.push(MsgBlock.fromContent('encryptedMsg', new Buf(Buf.concat(data))));
    }
    const sequentialProcessedBlocks: MsgBlock[] = []; // contains decrypted or otherwise formatted data
    for (const rawBlock of rawBlocks) {
      if ((rawBlock.type === 'signedMsg' || rawBlock.type === 'signedHtml') && rawBlock.signature) {
        const verify = await PgpMsg.verifyDetached({ sigText: Buf.fromUtfStr(rawBlock.signature), plaintext: Buf.with(rawSigned || rawBlock.content) });
        if (rawBlock.type === 'signedHtml') {
          sequentialProcessedBlocks.push({ type: 'verifiedMsg', content: Xss.htmlSanitizeKeepBasicTags(rawBlock.content.toString()), verifyRes: verify, complete: true });
        } else { // text
          sequentialProcessedBlocks.push({ type: 'verifiedMsg', content: Str.asEscapedHtml(rawBlock.content.toString()), verifyRes: verify, complete: true });
        }
      } else if (rawBlock.type === 'encryptedMsg' || rawBlock.type === 'signedMsg') {
        const decryptRes = await PgpMsg.decrypt({ kisWithPp, msgPwd, encryptedData: Buf.with(rawBlock.content) });
        if (decryptRes.success) {
          if (decryptRes.isEncrypted) {
            const formatted = await MsgBlockParser.fmtDecryptedAsSanitizedHtmlBlocks(decryptRes.content);
            sequentialProcessedBlocks.push(...formatted.blocks);
            subject = formatted.subject || subject;
          } else {
            // treating as text, converting to html - what about plain signed html? This could produce html tags
            // although hopefully, that would, typically, result in the `(rawBlock.type === 'signedMsg' || rawBlock.type === 'signedHtml')` block above
            // the only time I can imagine it screwing up down here is if it was a signed-only message that was actually fully armored (text not visible) with a mime msg inside
            // ... -> in which case the user would I think see full mime content?
            sequentialProcessedBlocks.push({ type: 'verifiedMsg', content: Str.asEscapedHtml(decryptRes.content.toUtfStr()), complete: true, verifyRes: decryptRes.signature });
          }
        } else {
          decryptRes.message = undefined;
          sequentialProcessedBlocks.push({
            type: 'decryptErr',
            content: decryptRes.error.type === DecryptErrTypes.noMdc ? decryptRes.content! : rawBlock.content,
            decryptErr: decryptRes,
            complete: true
          });
        }
      } else if (rawBlock.type === 'encryptedAtt' && rawBlock.attMeta && /^(0x)?[A-Fa-f0-9]{16,40}\.asc\.pgp$/.test(rawBlock.attMeta.name || '')) {
        // encrypted pubkey attached
        const decryptRes = await PgpMsg.decrypt({ kisWithPp, msgPwd, encryptedData: Buf.with(rawBlock.attMeta.data || '') });
        if (decryptRes.content) {
          sequentialProcessedBlocks.push({ type: 'publicKey', content: decryptRes.content.toString(), complete: true });
        } else {
          sequentialProcessedBlocks.push(rawBlock); // will show as encryptedAtt
        }
      } else {
        sequentialProcessedBlocks.push(rawBlock);
      }
    }
    const msgContentBlocks: MsgBlock[] = [];
    const blocks: MsgBlock[] = [];
    let replyType = 'plain';
    for (const block of sequentialProcessedBlocks) { // fix/adjust/format blocks before returning it over JSON
      if (block.content instanceof Buf) { // cannot JSON-serialize Buf
        block.content = isContentBlock(block.type) ? block.content.toUtfStr() : block.content.toRawBytesStr();
      } else if (block.attMeta && block.attMeta.data instanceof Uint8Array) {
        // converting to base64-encoded string instead of uint8 for JSON serilization
        // value actually replaced to a string, but type remains Uint8Array type set to satisfy TS
        // no longer used below, only gets passed to be serialized as JSON - later consumed by iOS or Android app
        block.attMeta.data = Buf.fromUint8(block.attMeta.data).toBase64Str() as any as Uint8Array;
      }
      if (block.type === 'decryptedHtml' || block.type === 'decryptedText' || block.type === 'decryptedAtt') {
        replyType = 'encrypted';
      }
      if (block.type === 'publicKey') {
        if (!block.keyDetails) { // this could eventually be moved into detectBlocks, which would make it async
          const { keys } = await PgpKey.normalize(block.content);
          if (keys.length) {
            for (const pub of keys) {
              blocks.push({ type: 'publicKey', content: pub.armor(), complete: true, keyDetails: await PgpKey.details(pub) });
            }
          } else {
            blocks.push({
              type: 'decryptErr',
              content: block.content,
              complete: true,
              decryptErr: {
                success: false,
                error: { type: 'format' as DecryptErrTypes, message: 'Badly formatted public key' },
                longids: { message: [], matching: [], chosen: [], needPassphrase: [] }
              }
            });
          }
        } else {
          blocks.push(block);
        }
      } else if (isContentBlock(block.type)) {
        msgContentBlocks.push(block);
      } else if (Mime.isPlainImgAtt(block)) {
        msgContentBlocks.push(block);
      } else if (block.type !== 'plainAtt') {
        blocks.push(block);
      }
    }
    const { contentBlock, text } = fmtContentBlock(msgContentBlocks);
    blocks.unshift(contentBlock);
    // data represent one JSON-stringified block per line. This is so that it can be read as a stream later
    return fmtRes({ text, replyType, subject }, Buf.fromUtfStr(blocks.map(b => JSON.stringify(b)).join('\n')));
  }
```

### PR DESCRIPTION
**Pull request by IvanPizhenko**
This PR introduces native Kotlin-base processing of the complex email messages

close #1057
----------------------------------
- Tests added

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities

### CODE REVIEW

**Comment by IvanPizhenko** [comment]
@tomholub I can see some **Snyk** tests failed, however I can't see what exactly. Please check.

**Comment by seisvelas** [comment]
@IvanPizhenko Sorry to answer a question not directed at me, but I checked on Snyk and it appears this PR introduces a vulnerable dependency. Specifically, `com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20200713.1`, which is introduced here:

https://github.com/FlowCrypt/flowcrypt-android/blob/0c43360e52b151e050376592bb492e49fd366eba/FlowCrypt/build.gradle#L459

Depends on a version of `com.google.guava` which suffers an Information Disclosure vulnerability (you can learn more about how this specific vuln works / can be exploited in Guava here: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415)

The codebase on https://github.com/OWASP/java-html-sanitizer has actually updated to a non-vulnerable Guava version (here: https://github.com/OWASP/java-html-sanitizer/commit/ad287c39f6102d875ad55ecab3094389bb3036d4), but there hasn't been a release in quite some time which is why we're having this problem.

The actual vulnerability is that files used in the temp dir created via Guava's `createTempDir` are readable by all users on the system. Upon deeper inspection, it appears `owasp-java-html-sanitizer` doesn't even use the vulnerable method, so in practice we should be safe. 

Consequently, I've told Snyk to skip this check and mark it as passed.

**Review by seisvelas — APPROVED** [review]

**Comment by tomholub** [comment]
Thank you Alex for looking into this :+1:

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt [hunk 1]
```diff
@@ -350,9 +344,186 @@ class PgpMsgTest {
...
       if (actualBlock.type in MsgBlock.Type.signedBlocks) {
         val expectedSignature = expectedBlock["signature"].asString.normalizeEol()
-        val actualSignature = ((actualBlock as SignedBlock).signature ?: "").normalizeEol()
+        val actualSignature = ((actualBlock as SignedMsgBlock).signature ?: "").normalizeEol()
         assertEquals(expectedSignature, actualSignature)
       }
     }
   }
+
+  // -------------------------------------------------------------------------------------------
```
Comment (tomholub) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt:353]: Approximately 14 test files (.txt) were added below, but this test is using only a handful of them. Where are they being loaded and used?

**Review by tomholub — COMMENTED** [review]
Thanks! So far only reviewed the tests. Sorry if the answer is obvious.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 2]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+    </style>
+  </head>
+  <body>$msgContentAsHtml</body>
+</html>"""
+      )
+    )
+  }
+
+  private val cidCorrectionRegex1 = Regex(">$")
+  private val cidCorrectionRegex2 = Regex("^<")
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:923]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 3]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+      }
+      startPos = match.range.last + 1
+    }
+    for (cid in usedCids) {
+      inlineImagesByCid.remove(cid)
+    }
+    return result.toString()
+  }
+
+  private val imgSrcWithCidRegex = Regex("src=\"cid:([^\"]+)\"")
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:970]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 4]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+
+  private val frameCssMap = mapOf(
+    FrameColor.GREEN to "border: 1px solid #f0f0f0;border-left: 8px solid #31A217;" +
+        "border-right: none;background-image: url(data:image/png;base64,${seamlessLockBg});",
+    FrameColor.GRAY to "border: 1px solid #f0f0f0;border-left: 8px solid #989898;" +
+        "border-right: none;",
+    FrameColor.RED to "border: 1px solid #f0f0f0;border-left: 8px solid #d14836;" +
+        "border-right: none;",
+    FrameColor.PLAIN to "border: none;"
+  )
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1005]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 5]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+    }
+
+    return cleanHtml2.replace(
+      imgContentReplaceable,
+      "<font color=\"#D14836\" face=\"monospace\">[img]</font>"
+    )
+  }
+
+  private const val innerTextTypeAttr = "data-fc-inner-text-type"
+  private const val fromImageAttr = "data-fc-is-from-image"
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1144]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 6]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+  }
+
+  private val brRegex = Regex("<br[^>]*>")
+  private val blockEndRegex = Regex(
+    "</(p|h1|h2|h3|h4|h5|h6|ol|ul|pre|address|blockquote|dl|div|fieldset|form|hr|table)[^>]*>"
+  )
+  private val blockStartRegex = Regex(
+    "<(p|h1|h2|h3|h4|h5|h6|ol|ul|pre|address|blockquote|dl|div|fieldset|form|hr|table)[^>]*>"
+  )
+  private val multiNewLineRegex = Regex("\\n{2,}")
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1246]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 7]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+  }
+
+  private fun generateRandomSuffix(length: Int = 5): String {
+    val rnd = Random(System.currentTimeMillis())
+    var s = rnd.nextInt().toString(16)
+    while (s.length < length) s += rnd.nextInt().toString(16)
+    return s.substring(0, length)
+  }
+
+  private val ALLOWED_ELEMENTS = arrayOf(
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1266]: :+1:

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 8]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+    }
+    if (i < decryptedContent.length) result.append(decryptedContent.substring(i))
+    return result.toString()
+  }
+
+  fun isFcAttachmentLinkData(obj: JSONObject?): Boolean {
+    return obj != null && obj.has("name") && obj.has("size") && obj.has("type")
+  }
+
+  private val fcAttachmentRegex = Regex(
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1351]: UPPER_CASE

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 9]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+    "<a\\s+href=\"([^\"]+)\"\\s+class=\"cryptup_file\"\\s+cryptup-data=" +
+        "\"([^\"]+)\"\\s*>[^<]+</a>\\n?"
+  )
+
+  fun stripFcReplyToken(decryptedContent: String): String {
+    return decryptedContent.replace(fcReplyTokenRegex, "")
+  }
+
+  private val fcReplyTokenRegex = Regex("<div[^>]+class=\"cryptup_reply\"[^>]+></div>")
```
Comment (DenBond7) [inline FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:1360]: UPPER_CASE

**Review by DenBond7 — CHANGES_REQUESTED** [review]
@IvanPizhenko Please look at my comments. I didn't try your realization yet but it will be a start point of the final migration. On the current stage it's hard to say what is good or not good.

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MimeUtils.kt [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+import java.util.Properties
+import javax.mail.Session
+import javax.mail.internet.MimeMessage
+
+object MimeUtils {
+  fun resemblesMsg(msg: ByteArray?): Boolean {
+    if (msg == null) return false
+    val firstChars = msg.copyOfRange(0, msg.size.coerceAtMost(1000))
+      .toString(StandardCharsets.US_ASCII)
+      .toLowerCase(Locale.ROOT)
```
Comment (tomholub) [inline FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MimeUtils.kt:23]: I wonder if the conversion to String can fail with an exception if we give it arbitrary bytes that are non-ascii. If it can fail by throwing, we should catch the error and return false.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt [hunk 11]
```diff
@@ -112,4 +124,85 @@ object PgpKey {
...
+            replacementKeyRing = PGPSecretKeyRing.insertSecretKey(
+              replacementKeyRing, replacementKey
+            )
+          }
+        }
+        if (replacementKeyRing !== keyRing) {
+          keys[keyRingIndex] = replacementKeyRing
+        }
+      }
+    }
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt:205]: Agree we should propose that Paul adds a method for this in the library. The reason for this code is that 1) 3rd party certification are ignored in our code anyway and 2) some keys can have 3rd party certification bloat that makes it difficult to work with the keys unless we removed them.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 12]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
   private val privateKeyRegex = Regex("(cryptup|flowcrypt)-backup-[a-z0-9]+\\.(key|asc)\$")
   private val publicKeyRegex1 = Regex("^(0|0x)?[A-F0-9]{8}([A-F0-9]{8})?.*\\.asc\$")
   private val publicKeyRegex2 = Regex("[A-F0-9]{8}.*\\.asc\$")
+  private val publicKeyRegex3 = Regex("^(0x)?[A-Fa-f0-9]{16,40}\\.asc\\.pgp$")
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:637]: I'm not too sure about any better way to call these. But since they test filenames, then maybe `publicKeyFilenameRegex1` .. ?

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt [hunk 13]
```diff
@@ -583,4 +634,741 @@ object PgpMsg {
...
+  ): ParseDecryptResult {
+    return if (isEmail) {
+      parseDecryptMsg(MimeUtils.mimeTextToMimeMessage(content), keys)
+    } else {
+      val blocks = listOf(MsgBlockFactory.fromContent(MsgBlock.Type.ENCRYPTED_MSG, content))
+      parseDecryptProcessedMsg(MimeProcessedMsg(blocks), keys)
+    }
+  }
+
+  fun parseDecryptMsg(msg: MimeMessage, keys: List<KeyWithPassPhrase>): ParseDecryptResult {
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:659]: Maybe you were talking about `parseDecryptProcessedMsg` ? It's true it's a bit long, but it mimics the TypeScript implementation pretty closely, which is also an advantage. Maybe let's not refactor it too much yet, but once the code is verified to be working and that we don't have to compare it to the original method to make fixes, then we could start working on refactor it to fit the style of this repo again.

To rephrase, I recommend to verify the code is stable and then make similar improvements after.

**Review by tomholub — COMMENTED** [review]
This PR is pretty massive :eyes: which reflects the issue is a complicated one. It looks good. On my end, I mainly want to make sure that all provided test cases are indeed tested (see earlier question) and if not, that we file an issue to test all soon.

**Comment by tomholub** [comment]
> @IvanPizhenko Please look at my comments. I didn't try your realization yet but it will be a start point of the final migration. On the current stage it's hard to say what is good or not good.

As long as it passes the supplied test cases, then it's well good enough. Of course, some adjustments will be needed once you start integrating, but if we confirm that supplied test cases pass the way they do on TypeScript code (and code style stuff gets adjusted) then this is perfectly fine for merging even if we didn't try to integrate it yet.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt (hunk 13 above)
[the remark this answers is not in the document]
Comment (DenBond7) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpMsg.kt:659]: > To rephrase, I recommend to verify the code is stable and then make similar improvements after.

Agree. Then I'm Ok with the current realization. We can improve it in a separate issue.

**Comment by IvanPizhenko** [comment]
> @IvanPizhenko Sorry to answer a question not directed at me, but I checked on Snyk and it appears this PR introduces a vulnerable dependency. Specifically, `com.googlecode.owasp-java-html-sanitizer:owasp-java-html-sanitizer:20200713.1`, which is introduced here:
> 
> https://github.com/FlowCrypt/flowcrypt-android/blob/0c43360e52b151e050376592bb492e49fd366eba/FlowCrypt/build.gradle#L459
> 
> Depends on a version of `com.google.guava` which suffers an Information Disclosure vulnerability (you can learn more about how this specific vuln works / can be exploited in Guava here: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-1015415)
> 
> The codebase on https://github.com/OWASP/java-html-sanitizer has actually updated to a non-vulnerable Guava version (here: [OWASP/java-html-sanitizer@ad287c3](https://github.com/OWASP/java-html-sanitizer/commit/ad287c39f6102d875ad55ecab3094389bb3036d4)), but there hasn't been a release in quite some time which is why we're having this problem.
> 
> The actual vulnerability is that files used in the temp dir created via Guava's `createTempDir` are readable by all users on the system. Upon deeper inspection, it appears `owasp-java-html-sanitizer` doesn't even use the vulnerable method, so in practice we should be safe.
> 
> Consequently, I've told Snyk to skip this check and mark it as passed.

Thanks Alex!

File: FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MimeUtils.kt (hunk 10 above)
Comment (IvanPizhenko) [reply FlowCrypt/src/main/java/com/flowcrypt/email/core/msg/MimeUtils.kt:23]: Did the small test:
```kotlin
import java.nio.charset.StandardCharsets
import java.util.Locale

fun main() {
    val a = ByteArray(256)
    for (i in 0..255) a[i] = i.toByte()
    val s = a.toString(StandardCharsets.US_ASCII).toLowerCase(Locale.ROOT)
    println(s)
}
```
Works for all source byte values.

File: FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt (hunk 11 above)
[the remark this answers is not in the document]
Comment (IvanPizhenko) [reply FlowCrypt/src/main/java/com/flowcrypt/email/security/pgp/PgpKey.kt:169]: agree. this is good candidate to move into PGPainless

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt (hunk 1 above)
Comment (IvanPizhenko) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt:365]: All these files should be used in the tests here.

Comment (IvanPizhenko) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt:365]: Looks like `mime-email-*.txt` are not used. Will remove them

**Comment by DenBond7** [comment]
@IvanPizhenko I've added some changes to fix tests

**Review by DenBond7 — APPROVED** [review]

**Review by tomholub — COMMENTED** [review]
I've reviewed the changes and they look good. I'll still give it a review regarding the test cases, then can merge.

File: FlowCrypt/src/test/resources/PgpMsgTest/compat/direct-encrypted-text.txt [hunk 14]
```diff
@@ -0,0 +1,14 @@
+-----BEGIN PGP MESSAGE-----
```
Comment (tomholub) [inline FlowCrypt/src/test/resources/PgpMsgTest/compat/direct-encrypted-text.txt:1]: This file is not used anywhere that I can find

File: FlowCrypt/src/test/resources/PgpMsgTest/compat/direct-encrypted-pgpmime.txt [hunk 15]
```diff
@@ -0,0 +1,36 @@
+-----BEGIN PGP MESSAGE-----
```
Comment (tomholub) [inline FlowCrypt/src/test/resources/PgpMsgTest/compat/direct-encrypted-pgpmime.txt:1]: This file is not used anywhere that I can find
