### PR TITLE
issue #1296 Add test for the invalid passphrase error

### LINKED ISSUE #1296: Android app not accepting passphrase used in Chrome extension
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXmdVSPcTvXfHmdBtTwZGRnnK

> Hello,
> I've successfully configured and used FlowCrypt with Chrome Extension.
> Unfortunately I was not able to import my secret key using FlowCrypt app on Android phone.
> The error message is "wrong pass phrase", although I've successfully used this phrase with FlowCrypt Chrome Extension already.
> May I ask you if FlowCrypt Android app supports PGP RSA 4096 bit keys?
> What is the maximal length of the pass phrase on Android?
> Are there any other restrictions on the pass phrase on Android in comparison to Chrome Extension?

In addition, the user clarified that it's very unlikely that the passphrase entered in the Android app is different, as they are using a password manager:

> I copy and paste the passphrase from the password manager (keepass2android) and I use the same password database on my PC with Chrome Extension.
> So yes, the passphrase is the same.

Do really long passphrases or 4096 bit keys cause problems on the app? Let me know how I can help troubleshoot this. Otherwise my plan is to just manually see how length becomes a problem on Android vs Chrome.

### PR DESCRIPTION
**Pull request by IvanPizhenko**
This PR adds unit test for the invalid passphrase error described in the #1296

close #1296

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities

### CODE REVIEW

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt [hunk 1]
```diff
@@ -6,11 +6,14 @@
 package com.flowcrypt.email.security.pgp
 
 import com.flowcrypt.email.BuildConfig
+import com.flowcrypt.email.extensions.kotlin.toHexString
 import com.flowcrypt.email.security.model.Algo
 import com.flowcrypt.email.security.model.KeyId
 import com.flowcrypt.email.security.model.PgpKeyDetails
 import org.junit.Assert.assertEquals
+import org.junit.Ignore
```
Comment (DenBond7) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:14]: Unused import

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt [hunk 2]
```diff
@@ -126,4 +129,16 @@ class PgpKeyTest {
...
+  fun testParseAndDecryptKey_Issue1296() {
+    val publicKeyRing = Utils.loadPublicKey("issue-1296-0xA96B4C55A800DB83.public.gpg-key")
+    val fingerprint = publicKeyRing.publicKey.fingerprint.toHexString()
+    val secretKeyRing = Utils.loadSecretKey("issue-1296-0xA96B4C55A800DB83.secret-subkeys.gpg-key")
+    assertEquals(fingerprint, secretKeyRing.publicKey.fingerprint.toHexString())
+    val passphrase = Passphrase.fromPassword("password12345678")
+    val decryptedSecretKeyRing = PgpKey.decryptKey(secretKeyRing, passphrase)
+    val decryptedKeyFingerprint = decryptedSecretKeyRing.publicKey.fingerprint.toHexString()
+    assertEquals(fingerprint, decryptedKeyFingerprint)
+  }
```
Comment (DenBond7) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:143]: Maybe it would be better to use PGPainless for the fingerprint comparison

```
@Test
  fun testParseAndDecryptKey_Issue1296() {
    val publicKeyRing = Utils.loadPublicKey("issue-1296-0xA96B4C55A800DB83.public.gpg-key")
    val expectedFingerprint = OpenPgpV4Fingerprint(publicKeyRing)
    val secretKeyRing = Utils.loadSecretKey("issue-1296-0xA96B4C55A800DB83.secret-subkeys.gpg-key")
    assertEquals(expectedFingerprint, OpenPgpV4Fingerprint(secretKeyRing.publicKey))
    val passphrase = Passphrase.fromPassword("password12345678")
    val decryptedSecretKeyRing = PgpKey.decryptKey(secretKeyRing, passphrase)
    assertEquals(expectedFingerprint, OpenPgpV4Fingerprint(decryptedSecretKeyRing.publicKey))
  }
```

Comment (DenBond7) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:143]: In that case, you don't need `ByteArray.toHexString`

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+
+package com.flowcrypt.email.security.pgp
+
+import org.bouncycastle.openpgp.PGPPublicKeyRing
+import org.bouncycastle.openpgp.PGPSecretKeyRing
+import org.pgpainless.PGPainless
+import java.nio.charset.Charset
+import java.nio.charset.StandardCharsets
+
+object Utils {
```
Comment (DenBond7) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt:15]: we already have a place for such code. Please look at `com.flowcrypt.email.util.TestGeneralUtil` and move code there.

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt [hunk 4]
```diff
@@ -13,30 +13,26 @@ import com.flowcrypt.email.extensions.kotlin.normalizeEol
...
 class PgpMsgTest {
-
   private data class MessageInfo(
     val key: String,
     val content: List<String>,
     val quoted: Boolean? = null,
     val charset: String = "UTF-8"
   ) {
-    val armored: String = loadResourceAsString("messages/$key.txt")
+    val armored: String = Utils.loadResourceAsString("messages/$key.txt")
```
Comment (DenBond7) [inline FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpMsgTest.kt:35]: :+1:

**Review by DenBond7 — CHANGES_REQUESTED** [review]
@IvanPizhenko Please look at my comments

File: .idea/gradle.xml [hunk 5]
```diff
@@ -1,21 +1,19 @@
...
           <set>
             <option value="$PROJECT_DIR$" />
             <option value="$PROJECT_DIR$/FlowCrypt" />
           </set>
         </option>
         <option name="resolveModulePerSourceSet" value="false" />
-        <option name="useQualifiedModuleNames" value="true" />
       </GradleProjectSettings>
     </option>
   </component>
```
Comment (DenBond7) [inline .idea/gradle.xml:19]: Also please add EOL

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt (hunk 1 above)
Comment (seisvelas) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:14]: Would it be easier to integrate a Kotlin linter into the Semaphore tests, that way we don't need to depend on manual review to catch little things like this?

Comment (tomholub) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:14]: Agree - there is #584 #1122 #545 . We should use software for this, not humans.

Comment (IvanPizhenko) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:14]: I remember we have a task for this, even one assigned to me #1122. So I will be working on it when more tasks are finished.

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt (hunk 2 above)
Comment (IvanPizhenko) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/PgpKeyTest.kt:143]: Hmm, maybe, will try.

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt (hunk 3 above)
Comment (IvanPizhenko) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt:15]: Unfortunately it gives build error when I move to that class. Note that `TestGeneralUtil`  is under `androidTest` and these tests are under `test`.

File: .idea/gradle.xml (hunk 5 above)
Comment (IvanPizhenko) [reply .idea/gradle.xml:20]: This is auto generated file by IntelliJ

**Comment by IvanPizhenko** [comment]
@DenBond7 please re-review

File: FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt (hunk 3 above)
Comment (DenBond7) [reply FlowCrypt/src/test/java/com/flowcrypt/email/security/pgp/Utils.kt]: ah... sorry. So we can leave it as-is

**Review by DenBond7 — APPROVED** [review]

**Review by seisvelas — APPROVED** [review]
